### ISSUE TITLE
IndexOutOfBoundsException in QR code reader

### ISSUE THREAD

**Issue by kazyx** [locana/locana#12]
at ZXing.PDF417.Internal.PDF417ScanningDecoder.getStartColumn(DetectionResult detectionResult, Int32 barcodeColumn, Int32 imageRow, Boolean leftToRight)
   at ZXing.PDF417.Internal.PDF417ScanningDecoder.decode(BitMatrix image, ResultPoint imageTopLeft, ResultPoint imageBottomLeft, ResultPoint imageTopRight, ResultPoint imageBottomRight, Int32 minCodewordWidth, Int32 maxCodewordWidth)
   at ZXing.PDF417.PDF417Reader.decode(BinaryBitmap image, IDictionary`2 hints, Boolean multiple)
   at ZXing.PDF417.PDF417Reader.decode(BinaryBitmap image, IDictionary`2 hints)
   at ZXing.MultiFormatReader.decodeInternal(BinaryBitmap image)
   at ZXing.BarcodeReader.Decode(LuminanceSource luminanceSource)
   at Locana.Pages.QrCodePage.Decode(SoftwareBitmap image, Boolean tryMultipleBarcodes)
   at Locana.Pages.QrCodePage.<GetPreviewFrameAsSoftwareBitmapAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Locana.Pages.QrCodePage.<<OnNavigatedTo>b__11_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by kazyx** [comment]
We cannot reproduce this now
