### ISSUE TITLE
Error toast on movie streaming

### ISSUE THREAD

**Issue by naotaco** [locana/locana#23]
It says "Failed to load contents list" after starting movie streaming

**Comment by naotaco** [comment]
```
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in KzRemoteApi.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in KzRemoteApi.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
Exception thrown: 'Kazyx.RemoteApi.RemoteApiException' in mscorlib.ni.dll
   at Kazyx.RemoteApi.ApiClient.<Core>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kazyx.RemoteApi.ApiClient.<Single>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kazyx.RemoteApi.AvContent.AvContentApiClient.<GetContentCountAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Locana.Playback.RemoteApiContentsLoader.<GetContentsOfDaySeparatelyAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Locana.Playback.RemoteApiContentsLoader.<GetContentsByDateSeparatelyAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Locana.Playback.RemoteApiContentsLoader.<Load>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Locana.Playback.Operator.CameraApiContentsOperator.<LoadContents>d__11.MoveNext()
Viewer_FailedToLoadContents
Hide Progress
Enqueue toast: Failed to load contents list
```

**Comment by kazyx** [comment]
Objective:
- Suppress toast while playing movie
- Retry contents loading later.
